version: "3.9"

services:
  db:
    image: postgres:15
    container_name: asset_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: examplepassword
      POSTGRES_DB: assetsdb
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./infra/init.sql:/docker-entrypoint-initdb.d/init.sql:ro  # ← 添加这行
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: asset_backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://postgres:examplepassword@db:5432/assetsdb
      JWT_SECRET: replace_with_secure_random_string
      ADMIN_USER: admin
      ADMIN_PASS_HASH: "$$2a$$10$$x8.1Jo5HKDdSnsQdPtrHjuI6Yt4yUyfA.H2b42H.u4d4eSFsArBxa"
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app

volumes:
  db_data:

